//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WeatherApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MainPage_LblTitle {
            get {
                return ResourceManager.GetString("MainPage_LblTitle", resourceCulture);
            }
        }
        
        internal static string MainPage_LblCity {
            get {
                return ResourceManager.GetString("MainPage_LblCity", resourceCulture);
            }
        }
        
        internal static string MainPage_PlaceHolderCity {
            get {
                return ResourceManager.GetString("MainPage_PlaceHolderCity", resourceCulture);
            }
        }
        
        internal static string MainPage_PlaceHolderEmail {
            get {
                return ResourceManager.GetString("MainPage_PlaceHolderEmail", resourceCulture);
            }
        }
        
        internal static string MainPage_lblInvalidEmail {
            get {
                return ResourceManager.GetString("MainPage_lblInvalidEmail", resourceCulture);
            }
        }
        
        internal static string MainPage_BtnGet {
            get {
                return ResourceManager.GetString("MainPage_BtnGet", resourceCulture);
            }
        }
        
        internal static string MainPage_LblLocation {
            get {
                return ResourceManager.GetString("MainPage_LblLocation", resourceCulture);
            }
        }
        
        internal static string MainPage_LblTemperature {
            get {
                return ResourceManager.GetString("MainPage_LblTemperature", resourceCulture);
            }
        }
        
        internal static string MainPage_LblWindSpeed {
            get {
                return ResourceManager.GetString("MainPage_LblWindSpeed", resourceCulture);
            }
        }
        
        internal static string MainPage_LblHumidity {
            get {
                return ResourceManager.GetString("MainPage_LblHumidity", resourceCulture);
            }
        }
        
        internal static string MainPage_LblVisibility {
            get {
                return ResourceManager.GetString("MainPage_LblVisibility", resourceCulture);
            }
        }
        
        internal static string MainPage_LblSunrise {
            get {
                return ResourceManager.GetString("MainPage_LblSunrise", resourceCulture);
            }
        }
        
        internal static string MainPage_LblSunset {
            get {
                return ResourceManager.GetString("MainPage_LblSunset", resourceCulture);
            }
        }
    }
}
